apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  FLASK_ENV: "production"
  CACHE_TTL_SECONDS: "300" # Configures Redis cache expiry
  API_BASE_URL: "http://webapp-service.default.svc.cluster.local"
